### ISSUE TITLE
Projectile Motion Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/projectile-motion#21]
## Design
- [x] **Sim folder and design doc created** (Date: 01/05/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
- [x] **Learning goals and standards identified** (Date: 07/28/2016)
- [x] **Design concept complete**  (Date: 01/08/2015)
- [x] **Wireframes complete** (Date: 01/26/2015) 
- [x] **Mockups complete** (Date: 07/27/2017) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 07/17/2017) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 08/11/2017) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped) #140
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] <s>Sim primer draft</s> (See #147)
  - [x] Verify credits #98
- [x] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) (See #147)

## Implementation
- [x] **Repository created** (Date: 01/07/2015)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ filesr
  - [x] (N/A) Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked to pull from rosetta to avoid conflicts.
- [x] **Development started** (Date: 07/08/2016)
- [x] **Sim is "feature complete"** (Date: 07/29/2017) 
- [x] **Code review completed** (Date: 08/11/2017) 
- [x] **Published** (Date: 08/23/2017) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 8/15/17) 
- [x] **First RC published** (Date: 8/15/17)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 8/23/17)

**Comment by pixelzoom** [comment]
I believe that @andrea-phet has completed all items related to implementation and testing. @arouinfar the remaining checklist items are yours.

**Comment by arouinfar** [comment]
@ariel-phet the only remaining item is "Features for PhET-iO Discussion". Is that relevant here, or can this issue be closed?

**Comment by ariel-phet** [comment]
Can be closed, closing.
